build: off
clone_depth: 5
configuration: Release

environment:
  PKG_NAME: pandas_plink
  CIBW_TEST_COMMAND: "python -c \"import %PKG_NAME%; import sys; sys.exit(%PKG_NAME%.test())\""
  matrix:
    - platform: x64
      ARCH: x64
      CIBW_SKIP: cp27-* cp34-* cp35-* *-win32

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/ci/master/appveyor.bat', 'appveyor.bat')" && appveyor.bat
  - pip install cibuildwheel>=0.10.0
  - cibuildwheel --output-dir wheelhouse
  - if [%APPVEYOR_REPO_TAG%]==[true] (pip install twine && twine upload --skip-existing wheelhouse/*)


artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
