# Skip .NET project specific build phase.
build: false

clone_depth: 5

platform:
    - x64

configuration: Release

environment:
    PKG_NAME: pandas_plink
    matrix:
    - PYTHON_VERSION: 2.7
      TARGET_ARCH: "x64"
      MINICONDA_PATH: C:\\Miniconda
      PYTHON_ARCH: "32"

install:
    - cmd: call %MINICONDA_PATH%\Scripts\activate.bat
    - cmd: appveyor-retry conda update --yes --quiet conda
    - cmd: appveyor-retry conda install --yes --quiet numpy scipy pandas pytest
    - cmd: pip install -r requirements.txt
    - cmd: pip install -r test-requirements.txt
    - cmd: python setup.py test && git clean -xdf
    - cmd: python setup.py install && git clean -xdf

test_script:
    - cmd: cd C:\
    - cmd: python -c "import sys; import %PKG_NAME%; sys.exit(%PKG_NAME%.test())"
