environment:
  CIBW_SKIP: cp27-* cp33-* cp34-* cp35-*

install:
  - set PATH=C:\Python37;C:\Python37\Scripts;%PATH%
  - cmd: python -m pip install cibuildwheel --upgrade

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmd: python -m cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        Invoke-Expression "python -m pip install twine"
        Invoke-Expression "python -m twine upload --skip-existing wheelhouse/*.whl"
      }

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
