environment:
  PKG_NAME: pandas_plink
  PYTHON: C:\Python37
  CIBW_TEST_COMMAND: "python -c \"import %PKG_NAME%; import sys; sys.exit(%PKG_NAME%.test())\""
  CIBW_SKIP: cp27-* cp33-* cp34-* cp35-*

install:
  - set PATH=%PYTHON%;%PATH%
  - cmd: python -m pip install cibuildwheel --upgrade

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/ci/master/appveyor.bat', 'appveyor.bat')" && appveyor.bat
  - cmd: python -m cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        Invoke-Expression "python -m pip install twine"
        Invoke-Expression "python -m twine upload --skip-existing wheelhouse/*.whl"
      }

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
