build: off
clone_depth: 4
configuration: Release

environment:
  PKG_NAME: pandas_plink
  CIBW_TEST_COMMAND: "python -c \"import %PKG_NAME%; import sys; sys.exit(%PKG_NAME%.test())\""
  matrix:
    - platform: x64
      ARCH: x64
      PYTHON: C:\\Python36-x64
      CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* *-win32

install:
    - "%PYTHON%\\python.exe -m pip install cibuildwheel>=0.9.2"

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/ci/master/appveyor.bat', 'appveyor.bat')" && appveyor.bat
    - cibuildwheel --output-dir wheelhouse
    - if [%APPVEYOR_REPO_TAG%]==[true] (%PYTHON%\python.exe -m pip install twine && %PYTHON%\python.exe -m twine upload --skip-existing wheelhouse/*)

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
