build: off
clone_depth: 5
platform: x64
configuration: Release

environment:
    PKG_NAME: pandas_plink
    PYTHON: "C:\\Python36-x64"

install:
    - dir %PYTHON%
    - dir %PYTHON%\\Scripts
    - dir %PYTHON%\\Lib
    - dir %PYTHON%\\libs
    - echo $PYTHONPATH%
    - set PATH=%PYTHON%;%PATH%
    - pip install -U wheel twine six pytest setuptools
    - cp requirements.txt ..\ && cd ..\
    - pip install -r requirements.txt -q
    - del requirements.txt && cd %APPVEYOR_BUILD_FOLDER%
    - python setup.py test
    - python setup.py install

test_script:
    - set PATH=%PYTHON%\\scripts;%PATH%
    - cd C:\
    - set T=import sys; import %PKG_NAME%; sys.exit(%PKG_NAME%.test())
    - python -c "%T%"
