# Skip .NET project specific build phase.
build: false

clone_depth: 5

platform:
    - x64

configuration: Release

environment:
    PKG_NAME: pandas_plink
    matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"
# init:
#     - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#     - echo %PYTHON_VERSION% %MINICONDA% %PYTHON_ARCH%

install:
    - set PATH="%MINICONDA%;%MINICONDA%\\Bin;%MINICONDA%\\Scripts;%PATH%"

    - cmd: call %MINICONDA%\Scripts\activate.bat
    - cmd: appveyor-retry conda update --yes --quiet conda
    - cmd: appveyor-retry conda install --yes --quiet numpy scipy pandas pytest
    - cmd: pip install -r requirements.txt
    - cmd: python setup.py install

test_script:
    - cmd: pip install -r test-requirements.txt
    - cmd: python -c "import sys; import %PKG_NAME%; sys.exit(%PKG_NAME%.test())"
    - cmd: python setup.py test
#
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
