language: python
matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
    python: '2.7'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.4'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.5'
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.5
before_install:
- wget https://raw.githubusercontent.com/Horta/travis-miniconda/master/install.sh
  -O install.sh
- chmod +x install.sh
- travis_retry bash -x ./install.sh
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
before_script:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- python setup.py test
script:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import pandas_plink; pandas_plink.test()"
- popd
branches:
  only:
  - master
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: MYKyYzeNnQnWW4bGLevdl0s3soI3GD2PVTk2OiqAOs1Sa253QUBMOLbNYjTkBBWENH2L2/HMJXnZZkZdAtqOh8WS7UNWqF6gxuSHUavqjZ7xoUex07uJtb4c1iLS9DsINDA/86dEgEuFCyFpAmPjAEPvq5Y8ycXAl3l38F8Amyv2Pcg3Z98MexkfGbSry7YKIblQ22ZnVGPfBcsaVg9MwqcFfaZhgdhm8ZxwsIJoaLM0nJx4qCmxiiju1oo5LDmJ4IvYO4G+QHmZ0ltGZvA484nIS3fKd/hyg1ub3vOdykqvq5g5FUT+kWPYGOA5h59rMnxetwrdBwVXaaXvN2sxi+J4mr0rR9AFTRQ+1InNHRwz31aaozWrAP5RMV4dHt5vme132hqQqrwgEns0ZwSuAJ6CiWvzeAmo+28NZFSFKHtwQPDBtp2bbNT3mZ1TAGjrPib5hmfs6HvRzWq1mpY3F3BlxTxgIRvYzJcJC80kZrVmgp0ZX6hpjanokCc6A+Ilk7v6w5JWkexaGH5YJMh2UCIkJS1OBVIvnkfCSx/L0jbKeeU9AcBDC60c0TTsWmy8dUGBUSzPQtkpiuHbnL2B3+piZkruH7j4G5eJgkb5FkAbCgr0PGiXDl+L8tSL1wCi65Wftde7ieu1oLSA/+EZ6CSentg4a4MNc2KKZenkFaE=
  on:
    distributions: sdist bdist_wheel
    repo: Horta/pandas-plink
