language: python
sudo: false
cache:
- pip
python:
- '2.7'
- '3.5'
- '3.6'
addons:
  apt:
    packages:
    - pandoc
    - python-cffi
install:
- pip install -r requirements.txt
script:
script:
- coverage run --source pandas-plink -m pytest
- python setup.py install
- pip uninstall pandas-plink --yes
- python setup.py sdist
- pip install dist/$(ls dist | grep -i -E '\.(gz)$' | head -1)
- pip uninstall pandas-plink --yes
after_success:
- codecov
notifications:
  email:
    recipients:
      - danilo.horta@gmail.com
    on_success: never
    on_failure: always
