language: python
sudo: required
dist: trusty
git:
  depth: 5
matrix:
  include:
  - python: 3.6
  - env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - os: osx
    language: generic
    env: PYENV=py27
  - os: osx
    language: generic
    env: PYENV=py36
before_install:
- travis_retry bash <(curl -s https://raw.githubusercontent.com/limix/travis-tools/master/get-travis-tools.sh)
- travis_retry travis/before-install.sh
install:
- travis_retry travis/install.sh
script:
- travis_retry travis/script.sh
after_success:
- travis_retry travis/after-success.sh
notifications:
  email:
    recipients:
      - danilo.horta@gmail.com
    on_success: change
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: uzRViMGz2OrzrrqQXKInTR376Gchl4pPUFOREVMbeApTjZd8GdfFMtc7qCwey5uCRWCBaqCIROoBqi6yb5nY7NZwzoS4o0AzUqDVJ+uRfb62v/kJrdfbiDQI1106ZvU/SqmHAxObmaORFZwWSTS6LjHcyc2ALKSTpzJitEtnb2mvltgui6NmJT6AxcjWS4d7ybHevSZ2j8Ii2a2dJHB5/1K4iQKDKS/whNwDiIy6+zpGdSPg/S7dx1Jh7SXV+nGye0pGaEBRR+sfKv1vgfo4nb+Z1giDJ1iotk6mPJlRY7cL3U3BFYpoQYYbEE8ZYZyutqnYiBgNwEJ+WlM/LwpEhqWwdulrgjCm62royE7H7G4QWriCdFQ3UVzn5Gm1fqbV6HlE5Zg/WjrNFeZrmqB/g9OmsgLWE6T/kV44boatbUfuJGveKXO7VR8dhx6k2tSR2wB1Ta3Aoi4vcDl2GXp8Z2kegi3MBAWgCTzPgqeRY9Qggkh1VCTQy/7Ly+XpzhA8H37tufvtp9mcwNrajyDfR4DSHyg9GafvNMnxcHo7vO9D2WZrXYqfCATq7Za3A41+SdSR96658Pbw6e5lTm9Y5BdPQQTz/lP1b2dEKAMU7EWSTFCRDDouWJwy2njaCScpvlo8Ra0OCYR2SVqENO8cbTFYnfu/lftHhnhWMwVd+9g=
  on:
    repo: limix/pandas-plink
    branch: master
    tags: true
env:
  global:
    - secure: azfHKw5UiF54CnDOME55bQRqNpS0PJk0Y60oeyMlnqnFm1h6eur3u6XZgg8431+aI05vRb9YOqLlbEegXuC1LNaKTJOrLsQlNfITdfPea6qS+bevPnNoWbbnf08s86NdxFs5Ol9WiTebNgdh6psMBIXiwcWWt/jkQLhTWK/8vk09zF7CBGRWPxgzsszMNqSlk4Yykgsq7DNm/4Ua0QyigDSEpvdCAAbCTt13P5dOt4mAH40E53caY8Ur1Hi8IFTE6YVwAIQ47dGta/kLSL+CQOc0Ue0oPyrefIVdJM/u/NiHp3NznQ75zVvY81JVESGNumom7DZmj5JfVj+Ewn9w9kZuAQNwGM4t0DUfZ/MhGriJxfIZ0ERHdFpPvM+SgC1KVZRobnRXnSYvmQ7JY+mR34tu5/2beNvKYg/bWCyoHISNCPsJbc1kqsTKlo8pEXTSNWIhT7k1By3bRmGrjU6ncmGVoPvvmd5VE7Lilh6iG6BJSfsFeRM96ip3/w+pEc0BbukVxomuRBqVTDdlNXXBcs4OIVBOJv+XvApQ7GmcgOO1g109eiULAXMjh/+z/0pQfN1Tzgp9RGt2xZOze741W+BmLXCKZyowDiYUZchFnVhVrlgtRMyH9Bt9gf2BlIJ1pJ+YSku/e19ZwyyUAYDXlvf6K8H+NBpLvonFGKcAZNc=
