language: python
sudo: false
cache:
- pip
python:
- '2.7'
- '3.5'
- '3.6'
addons:
  apt:
    packages:
    - pandoc
    - libffi-dev
    - libffi6
before_install:
- python -c "import setuptools; print(setuptools.__version__)"
- pip install -U setuptools -q
- python -c "import setuptools; print(setuptools.__version__)"
- pip install -r requirements.txt
install:
- pwd
- ls
- cat requirements.txt
- which pip
- pip install -r requirements.txt -q
- pwd
- ls
script:
- coverage run --source pandas-plink -m pytest
- python setup.py install
- pip uninstall pandas-plink --yes
- python setup.py sdist
- pip install dist/$(ls dist | grep -i -E '\.(gz)$' | head -1)
- pip uninstall pandas-plink --yes
after_success:
- codecov
notifications:
  email:
    recipients:
      - danilo.horta@gmail.com
    on_success: never
    on_failure: always
