language: python
sudo: required
dist: trusty
git:
  depth: 5
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
before_install:
- travis_retry travis/install_pandoc.sh
script:
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import sys; import pandas_plink; sys.exit(pandas_plink.test())"
- popd
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: uzRViMGz2OrzrrqQXKInTR376Gchl4pPUFOREVMbeApTjZd8GdfFMtc7qCwey5uCRWCBaqCIROoBqi6yb5nY7NZwzoS4o0AzUqDVJ+uRfb62v/kJrdfbiDQI1106ZvU/SqmHAxObmaORFZwWSTS6LjHcyc2ALKSTpzJitEtnb2mvltgui6NmJT6AxcjWS4d7ybHevSZ2j8Ii2a2dJHB5/1K4iQKDKS/whNwDiIy6+zpGdSPg/S7dx1Jh7SXV+nGye0pGaEBRR+sfKv1vgfo4nb+Z1giDJ1iotk6mPJlRY7cL3U3BFYpoQYYbEE8ZYZyutqnYiBgNwEJ+WlM/LwpEhqWwdulrgjCm62royE7H7G4QWriCdFQ3UVzn5Gm1fqbV6HlE5Zg/WjrNFeZrmqB/g9OmsgLWE6T/kV44boatbUfuJGveKXO7VR8dhx6k2tSR2wB1Ta3Aoi4vcDl2GXp8Z2kegi3MBAWgCTzPgqeRY9Qggkh1VCTQy/7Ly+XpzhA8H37tufvtp9mcwNrajyDfR4DSHyg9GafvNMnxcHo7vO9D2WZrXYqfCATq7Za3A41+SdSR96658Pbw6e5lTm9Y5BdPQQTz/lP1b2dEKAMU7EWSTFCRDDouWJwy2njaCScpvlo8Ra0OCYR2SVqENO8cbTFYnfu/lftHhnhWMwVd+9g=
  on:
    repo: limix/pandas-plink
    branch: 1.1.x
