language: python
python: 3.8
env:
  global:
    - URL=https://raw.githubusercontent.com/horta/ci/master
    - CIBW_SKIP="pp* cp27-* cp34-* cp35-* cp36-* *i686* *-win32"
    - CIBW_BEFORE_BUILD="python -m pip install numpy && python -m pip install pandas"
    - CIBW_TEST_COMMAND="python -c \"import pandas_plink; import sys; sys.exit(pandas_plink.test())\""
matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
    - os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - python3 -m pip install --upgrade pip setuptools
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.6
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe
        - python3 -m pip install certifi
          # Temporary fix: for https://github.com/joerick/cibuildwheel/issues/452
        - export SSL_CERT_FILE=`python3 -c "import certifi;print(certifi.where())"`
        - echo $SSL_CERT_FILE
addons:
  apt:
    packages:
      - libffi-dev
      - libffi6
      - cmake
install:
  - curl -fsSL $URL/check-readme.sh | bash
  - curl -fsSL $URL/py-check-style.sh | bash
  - python3 -m pip install --upgrade isort
  - flake8 pandas_plink
  - black --check pandas_plink
  - isort --check-only pandas_plink
  - pip install -e .
  - curl -fsSL $URL/py-dev-test.sh | bash
  - curl -fsSL $URL/py-sdist-test.sh | bash
  - python3 -m pip install cibuildwheel
script:
  - python3 -m cibuildwheel --output-dir wheelhouse
after_success:
  - |
    if [ "${TRAVIS_TAG:-}" != "" ]; then
      python3 -m pip install twine -U
      python3 -m twine upload --skip-existing wheelhouse/*
      python3 setup.py sdist
      python3 -m twine upload --skip-existing dist/*
    fi
notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
